[project]
name = "viconreader"
version = "0.1.0"
description = "This is a package to read in Vicon data for analysis."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.6",
    "numpy>=2.3.3",
    "pandas>=2.3.2",
    "scipy>=1.16.2",
]
